# Arreglos y clases
## Matrices
Las matrices son un arreglo de tamaño mxn.

\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}

In [1]:
# Creando una lista de listas
A=[[1,2,3],[4,5,6],[7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
type(A)

list

In [12]:
# Creamos otra lista de listas
B = [[21,34,40],[71,17,77],[73,81,28]]
A+B # Se pegan las listas

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]

In [5]:
# Se le suma A a A como en el apartado anterior
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
# Para ingresar a un elemento utilizas su etiqueta, 0, 1, 2... y luego la etiqueta del valor de la lista de adentro, ej:
A[0][0] # Manera correcta.
# "A[0,0]" Esto es un error, así no se puede ingresar a los elementos.

1

## Vectores y listas

Para poder sumar matrices es necesario que sean del mismo tamaño.



In [13]:
L = A[0]
M = B[0]

In [14]:
a = L[0]
b = M[0]
a + b

22

In [15]:
a == 1

True

### Suma de "vectores"

In [ ]:
len(L)==len(M) # Comparar la longitud de ambas listas para ver que sean iguales, si no no se puede sumar,.

In [17]:
suma = [L[0]+M[0], L[1]+M[1], L[2]+M[2]] # Sumar peras con peras y manzanas con manzanas, es decir en las respectivas posiciones de la matriz.
suma

[22, 36, 43]

In [18]:
suma=[L[i]+M[i] for i in range(3)]
suma

[22, 36, 43]

### Creación de funciones globales
La función para crear funciones es `def` que se cierra con un debug (`print` o `return`)

In [20]:
def Hola():
  print("Hola, me llamo Álvaro")

In [21]:
Hola()

Hola, me llamo Álvaro


In [24]:
def Saludar(s,n):
  print(f"Hola me llamo {s} y tengo {n} años")

In [25]:
Saludar("Álvaro", 18)

Hola me llamo Álvaro y tengo 18 años


In [38]:
def par():
  for x in range(10):
    if x%2==0:
      print(f"{x} es par")
    else:
        print(f"{x} es impar")

In [39]:
par()

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [40]:
# Dentro de la definición se puede introducir variables.
def suma_vectorial(L,M):
  x = [L[i]+M[i] for i in range(len(L))]
  return x

In [41]:
L = [1, 2, 3]
M = [21, 34, 40]

suma_vectorial(L,M)

[22, 36, 43]

### Módulos o librerías
Módulo: En muchos lenguajes de programación, un módulo es un archivo que contiene código que se puede importar y usar en otro programa. Puede contener clases, funciones, variables, etc. Los módulos ayudan a organizar el código en partes más pequeñas y manejables.

In [44]:
import math
from math import sqrt, pi

In [45]:
sqrt(68)

8.246211251235321

In [47]:
pi

3.141592653589793

# El módulo NumPy
La función `array`, convertir listas en un vector.

In [48]:
import numpy as np

L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [51]:
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [52]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])